"""
Configuration template - copy and modify as needed.

To use custom configuration, modify the values below and import
from this file instead of config.py
"""

from pathlib import Path
from typing import Optional

# ============================================================================
# PATHS CONFIGURATION
# ============================================================================

# Root workspace directory
WORKSPACE_ROOT = Path(__file__).parent

# Directory where agents will be created
AGENTS_DIR = WORKSPACE_ROOT / "agents"

# Templates directory (for future features)
TEMPLATES_DIR = WORKSPACE_ROOT / "templates"


# ============================================================================
# FILE NAMING
# ============================================================================

# Main prompt file for each agent
PROMPT_FILE = "prompt.txt"

# Python solution file generated by agents
SOLUTION_FILE = "solution.py"

# Log file for general output
LOG_FILE = "log.txt"

# Error file for failures and exceptions
ERROR_FILE = "error.txt"

# Test results in JSON format
TEST_RESULTS_FILE = "test_results.json"

# Dependency manifest for each agent
REQUIREMENTS_FILE = "requirements.txt"

# Marker for exported components
COMPONENT_MARKER = "__component_marker__"


# ============================================================================
# TIMEOUT SETTINGS (in seconds)
# ============================================================================

# Default timeout for code execution
DEFAULT_TIMEOUT = 300  # 5 minutes

# Minimum allowed timeout
MIN_TIMEOUT = 30  # 30 seconds

# Maximum allowed timeout
MAX_TIMEOUT = 3600  # 1 hour


# ============================================================================
# RECURSION SETTINGS
# ============================================================================

# Default maximum recursion depth
DEFAULT_RECURSION_DEPTH = 5

# Absolute maximum recursion depth
MAX_RECURSION_DEPTH = 10

# Default number of retry attempts for code generation
DEFAULT_MAX_RETRIES = 3


# ============================================================================
# LOGGING SETTINGS
# ============================================================================

# Log message format
LOG_FORMAT = "[{timestamp}] [{level}] {message}"

# Whether to log to console in addition to files
CONSOLE_LOG = True

# Log level (0=debug, 1=info, 2=warning, 3=error)
DEFAULT_LOG_LEVEL = 1


# ============================================================================
# NAMING CONVENTIONS
# ============================================================================

# Prefix for child agent folders (prevents name conflicts)
CHILD_FOLDER_PREFIX = "task_"

# Whether to sanitize folder names
SANITIZE_FOLDER_NAMES = True


# ============================================================================
# TESTING CONFIGURATION
# ============================================================================

# Timeout for individual pytest tests (seconds)
PYTEST_TIMEOUT = 60

# Pytest command-line options
PYTEST_OPTIONS = [
    "-v",
    "--tb=short",
]


# ============================================================================
# SYSTEM PROMPT TEMPLATE
# ============================================================================

SYSTEM_PROMPT_TEMPLATE = """You are a recursive code agent that decomposes tasks into subtasks and generates Python code.

## Core Principles:
1. **Task Decomposition**: Break down the given prompt into logically distinct subtasks
2. **Code Generation**: Write Python code for the current task level in `solution.py`
3. **Type Safety**: All functions must have complete type hints and docstrings
4. **Testing**: Validate your code works correctly before completion
5. **Error Reporting**: Log errors to `error.txt` for parent agent review
6. **Child Spawning**: For subtasks that are too complex, create child agents in named subfolders

## Code Requirements:
- Write multiple descriptively-named functions (not a single function)
- Use Google-style docstrings with parameter and return type documentation
- Include type hints on all function parameters and returns
- Prefix private functions with underscore
- Write pytest-compatible tests in a `test_solution.py` file
- Ensure all code is self-contained within `solution.py`
- If you use non-stdlib dependencies, list them in `requirements.txt` (one per line)

## Logging:
- Write progress and debugging info to `log.txt`
- Write errors and failures to `error.txt`
- Include timestamps in log entries
- Report child agent status to parent via these files

## Child Agents:
- Create child agents only if subtask is too complex to handle at current level
- Name child folders as: {CHILD_FOLDER_PREFIX}<descriptive_name>
- Pass appropriate timeout value in child prompt
- Child agents inherit the same system prompt and requirements

## Execution:
- Timeout: {timeout_seconds} seconds
- Max retries: {max_retries}
- Recursion depth: {recursion_depth}

Do not ask for clarification; proceed with task decomposition and code generation."""


# ============================================================================
# ADVANCED SETTINGS
# ============================================================================

# Enable experimental features
EXPERIMENTAL_FEATURES = False

# Enable performance profiling
ENABLE_PROFILING = False

# Maximum memory usage for child agents (MB, 0 = unlimited)
MAX_MEMORY_PER_AGENT = 0

# Whether to preserve intermediate files for debugging
PRESERVE_TEMP_FILES = False

# Email/webhook for notifications (future feature)
NOTIFICATION_ENDPOINT: Optional[str] = None

# Whether to enable parallel child agent execution
ENABLE_PARALLEL_CHILDREN = False

# Maximum number of parallel child agents
MAX_PARALLEL_CHILDREN = 4
